name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.25.1

    - name: Check formatting
      run: |
        go fmt ./...
        git diff --exit-code

    - name: Vet code
      run: go vet ./...

    - name: Test
      run: go test ./...
